#!/usr/bin/env python
# coding: utf-8

# In[1]:


import win32com.client
import pandas as pd
import pytz


# In[4]:


# inicializar o objeto Outlook
outlook = win32com.client.Dispatch("Outlook.Application").GetNamespace("MAPI")

# selecionar a pasta de emails
inbox = outlook.GetDefaultFolder(6)

# buscar os emails que correspondem ao filtro
emails = inbox.Items

# criar uma lista para armazenar os dados de cada email
data = []


# In[5]:


for email in emails:
    if email.UnRead == False and "" in email.Subject:
        
    # armazenar os dados relevantes em variáveis
        subject = email.Subject
        sender = email.SenderEmailAddress
        received_time = email.ReceivedTime
        body = email.body
        
    # remover o fuso horário e armazenar como string
        local_tz = pytz.timezone('America/Sao_Paulo')
        received_time_local = received_time.astimezone(local_tz)
        received_time_str = received_time_local.strftime('%Y-%m-%d %H:%M:%S')

    # adicionar os dados à lista
        data.append([subject, sender, received_time_str, body])


# In[7]:


# criar um dataframe do pandas com os dados
df = pd.DataFrame(data, columns=['Assunto', 'Remetente', 'Data de Recebimento', 'Corpo do Email'])


# In[9]:


# exportar o dataframe para Excel
df.to_excel('emails.xlsx', index=False)
